INSERT INTO OPERATION_TYPE VALUES(1, 'COMPRA A VISTA', -1);
INSERT INTO OPERATION_TYPE VALUES(2, 'COMPRA PARCELADA', -1);
INSERT INTO OPERATION_TYPE VALUES(3, 'SAQUE', -1);
INSERT INTO OPERATION_TYPE VALUES(4, 'PAGAMENTO', 1);